### ISSUE TITLE
Running app.py produces 404 error

### ISSUE THREAD

**Issue by crypdick** [plotly/dash-stock-tickers-demo-app#11]
I cloned the repo and ran `app.py` and I get the following messages:

Console:
```
 * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 704-832-824
127.0.0.1 - - [10/Feb/2018 15:01:44] "GET / HTTP/1.1" 404 -
```

The local site just shows a 404 error.

**Comment by chriddyp** [comment]
The `base_url_pathname` is set to `/dash/gallery/stock-tickers/` here: https://github.com/plotly/dash-stock-tickers-demo-app/blob/master/app.py#L14, so you'll actually need to visit http://localhost:8050/dash/gallery/stock-tickers

**Comment by crypdick** [comment]
Thank you, @chriddyp. If I add that to the README would you accept a PR?

**Comment by chriddyp** [comment]
yup!
