### ISSUE TITLE
Graph does not show up on page after updateGraph callback function returns

### ISSUE THREAD

**Issue by zanoo** [plotly/dash-stock-tickers-demo-app#16]
I just cloned this and switched over from Google Finance data to Robinhood data (e.g. see here: http://pandas-datareader.readthedocs.io/en/latest/remote_data.html#remote-data-robinhood). I verified that the returned DataFrame is populated, and that I'm encountering no exceptions. However, when the `updateGraph` callback function returns, I don't see the graph on the page. No error messages show up; it's just blank. I haven't changed any of the input/output dependencies, and I've verified that the data comes through from Robinhood (using Pandas DataReader) and can be graphed with plotly in a Jupyter notebook. It seems there's something wrong. I've also tried modifying this project to use local data from a SQL server, and the same issue arises. Any idea what's going wrong?

**Comment by bcdunbar** [comment]
@zanoo for robinhood to work there a few syntax changes that are required:

add `str(s[1])`
```
dcc.Dropdown(
    id='stock-ticker-input',
    options=[{'label': s[0], 'value': str(s[1])}
             for s in zip(df_symbol.Company, df_symbol.Symbol)],
    value=['YHOO', 'GOOGL'],
    multi=True
),
```

change DataReader to:
```
df = DataReader(str(ticker), 'robinhood').reset_index()
``` 
and any subsequent changes to plotting values, such as:
```
'x': df['begins_at'],
'open': df['open_price'],
'high': df['high_price'],
```

That ought to get it working for you.
