### ISSUE TITLE
App has stopped working

### ISSUE THREAD

**Issue by jackparmer** [plotly/dash-stock-tickers-demo-app#20]
https://dash-stock-tickers.plot.ly/

Originally reported by @cpsievert

**Comment by josegonzalez** [comment]
Looks like it works for me now? The first load took a while.

Maybe related is #18, which fixed local build issues.

**Comment by xhlulu** [comment]
Testing the app on local right now. The problem seems to come from pandas's `DataReader`; it seems to be stuck in an endless loop retrying to connect, and doesn't timeout.

**Comment by bcdunbar** [comment]
It may be worth moving examples away from pandas' DataReader as it seems to fail often nowadays.

**Comment by xhlulu** [comment]
Indeed, the documentation is pretty unclear. For example, `timeout` parameter doesn't do anything at all for class `pandas_datareader.mstar.daily.MorningstarDailyReader`, which is important when the requests takes a long time to process.
