### ISSUE TITLE
can not see graphs at all... tried python 2 and python 3...

### ISSUE THREAD

**Issue by koren88i** [plotly/dash-stock-tickers-demo-app#30]
C:\Users\koren\AppData\Local\Programs\Python\Python37\python3.exe C:/Users/koren/.PyCharmCE2017.3/config/scratches/scratch_9.py
 * Serving Flask app "stock-tickers" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 177-341-118
 * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)
127.0.0.1 - - [15/Sep/2018 17:15:33] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [15/Sep/2018 17:15:35] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [15/Sep/2018 17:15:35] "GET /_dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [15/Sep/2018 17:15:35] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [15/Sep/2018 17:15:35] "GET /favicon.ico HTTP/1.1" 200 -
127.0.0.1 - - [15/Sep/2018 17:15:42] "POST /_dash-update-component HTTP/1.1" 200 -

**Comment by lokkipeli** [comment]
It didn't work for me either no graphs

Unhandled Promise Rejection: TypeError: Plotly.react is not a function. (In 'Plotly.react(n,r.data,(0,s.clone)(r.layout),i)', 'Plotly.react' is undefined)

**Comment by ajrazander** [comment]
No graphs are showing for me either. I'm running it in python3. I added some debugging print statements though. The graph dataframes are populated with the correct data. The size of the list of graphs is the right length but still not graphs.

**Comment by ajrazander** [comment]
I commented out line 16
`dcc._js_dist[0]['external_url'] = 'https://cdn.plot.ly/plotly-finance-1.28.0.min.js'`
and the plots worked! Hopefully that works for you to @valuquant

**Comment by xhluca** [comment]
Issue is fixed by: https://github.com/plotly/dash-stock-tickers-demo-app/commit/01643c94d1430351778bb5dbd2e7e7938f5cfbd0

**Comment by xhluca** [comment]
Thank you for raising the issue!
