### ISSUE TITLE
TypeError: Dash() got an unexpected keyword argument 'assets_external_scripts'

### ISSUE THREAD

**Issue by aarjaneiro** [plotly/dash-stock-tickers-demo-app#39]
Setting `app.scripts.config.serve_locally = True` (instead of false) fixed this; running app.py alone would result in error otherwise.

**Comment by aarjaneiro** [comment]
Note, still receive traceback error `TypeError: can only concatenate list (not "str") to list`

**Comment by sawall** [comment]
Make sure that you are running python2 and install from the older library versions in requirements.txt. This package hasn't been updated in a while and some of the dependencies have not been updated for python3.

**Comment by BrandonChiazza** [comment]
the dash.py file does not accept the specified, meaning that the argument referenced in app.py is incorrect. 

When you open the dash.py file and look at the acceptable arguments, you'll see that 'external_scripts' is the expected argument.  Update your app.py file to:

app = dash.Dash(
    __name__, 
    **external_scripts='https://cdn.plot.ly/plotly-finance-1.28.0.min.js'**

)

________________________________

![image](https://user-images.githubusercontent.com/9555936/108583197-db86b000-7305-11eb-959f-227afd6b68a6.png)
