### ISSUE TITLE
Rangeslider

### ISSUE THREAD

**Issue by alrghods** [plotly/dash-stock-tickers-demo-app#8]
Hello,
I am working on some time series data and I'm using Dash to make a cool app. I want to my scatter plot has rangerslider like your plot. I could not figure it how you made it. Is the rangerslider comes with candlestick plot or I can have it with the scatter plot too? 
I tried this but it didn't work:
```
traces =[{

		'x':df.index,

		'y':df.level,

		'type': 'scatter', 'mode': 'lines',
		'name': 'a_level'
	}]
	graphs.append(dcc.Graph(
		id='a_level',
		figure={
			'data': traces,
			'layout': {
					'type': 'date',
					'rangeslider': {'visible':True},
                                        'margin': {'b': 0, 'r': 10, 'l': 60, 't': 0}
            }
		}
	)

```

Thank you in advance for your help

**Comment by bcdunbar** [comment]
@alrghods the correct syntax would be something like:

```
'data': [{
     'x': df.index,
     'y': df.level,
     'type': 'scatter',
 }],
'layout': {
     'xaxis': {
         'rangeslider': {}
      }
 }
```

Also, see here for additional examples https://plot.ly/python/range-slider/

For future reference, it would be better posting these types of questions on the community forum https://community.plot.ly/ You'd get better traction there.
